name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build the Go application
        run: GOOS=linux GOARCH=amd64 go build -o app .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/my-go-app:${{ github.sha }} -f docker/Dockerfile --push .
          docker push ghcr.io/${{ github.repository_owner }}/my-go-app:${{ github.sha }}

      - name: Clean up unused Docker images
        run: docker image prune -f
