name: Build and Deploy Go App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Extract module name
        id: extract-module-name
        run: echo "MODULE_NAME=$(grep '^module ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

      - name: Build the Go app
        run: GOOS=linux GOARCH=amd64 go build -o app .

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/$MODULE_NAME:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/$MODULE_NAME:latest
