name: Build and Deploy Go App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build the Go app
        run: GOOS=linux GOARCH=amd64 go build -o app .

      - name: Build Docker image
        run: |
          echo "FROM scratch
          COPY app /app
          ENTRYPOINT [\"/app\"]" > Dockerfile
          docker build -t ghcr.io/${{ github.repository }}/my-go-app:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/my-go-app:latest
